var paths = [
    { url: "/home", title: "home-section" },
    { url: "/middle-east", title: "middleEast-section" },
    { url: "/world", title: "world-section" },
    { url: "/sport", title: "sport-section" },
    { url: "/tennis", title: "tennis-section" },
    { url: "/motorsport", title: "motorsport-section" },
    { url: "/basketball", title: "basketball-section" },
    { url: "/football", title: "football-section" },
    { url: "/matches", title: "matches-section" },
    { url: "/standings", title: "standings-section" },
    { url: "/leagues", title: "leagues-section" },
    { url: "/competition/10", title: "competition-detial-ucl" },
    { url: "/team/662", title: "team-detail-manu" },
    { url: "/match/2462891", title: "match-detail-manu-vs-spurs" },
    { url: "/business", title: "business-section" },
    { url: "/technology", title: "technology-section" },
    { url: "/varieties", title: "varieties-section" },
    { url: "/livestream", title: "livestream" },
    { url: "/programs", title: "programs-list" },
    { url: "/hadithalarabi", title: "programs-detail-hadith-al-arab" },
    { url: "/episode/-TZa7REZzQ8/PLPMXgosg0OYM07Bj8adqqhh3vul6Z2t3o?headline=الأكاديمي%20والباحث%20المغربي%20محمد%20نور%20الدين%20أفاية%20ضيف%20حديث%20العرب&programName=حديث%20العرب&imageUrl=https://i.ytimg.com/vi/-TZa7REZzQ8/hqdefault.jpg", title: "episode-detail" },
    { url: "/blog", title: "blog-list" },
    { url: "/blog/994244", title: "blog-detail" },
    { url: "/topic", title: "topic-list" },
    { url: "/topic/774470", title: "topic-detail-varities" },
    { url: "/staticpage/6713", title: "static-page-detail-about-sna" },
    { url: "/article/995223", title: "article-detail" },
    { url: "/video", title: "video-list" },
    { url: "/video/995212", title: "video-detail" },
    { url: "/image_gallery", title: "image-gallery-list" },
    { url: "/image_gallery/991966", title: "image-gallery-detail" },
    { url: "/infographic", title: "infographic-list" },
    { url: "/infographic/987649", title: "infographic-detail" },
    { url: "/markets", title: "markets-section" },
    { url: "/currencies", title: "currencies-section" },
    { url: "/marketdetail/abd", title: "market-detail-abudhabi" },
    { url: "/commodities", title: "commodities-section" },
    { url: "/search?q=sky", title: "search-sky" }
];

exports.paths = paths;